### ISSUE TITLE
Problem to properly initialize PS on a scroll container removed by ngIf

### ISSUE THREAD

**Issue by moniuch** [zefoy/ngx-perfect-scrollbar#174]
My component, which uses ngx-perfect-scrollbar directive, sometimes is initialized while being hidden (under a false *ngIf). When the condition becomes back `true`, the component's scroll appears at the left side. 
![screen shot 2018-03-26 at 11 46 23](https://user-images.githubusercontent.com/681956/37901129-a897a640-30f0-11e8-90d4-340d6f551635.png)

I have tried to explicitly call `.update()` but to no avail - actually, none of the public methods exposed by the directive (such as `.scrollToBottom()`) would work.

This is what I have tried:

```html
<my-container *ngIf="someCondition">
  <div class="list-wrapper" [perfectScrollbar]="scrollConfig" #ps="ngxPerfectScrollbar">
    <my-list></my-list>
  </div>
</my-container>
```

```ts
@ViewChild('ps') ps: PerfectScrollbarDirective;

ngAfterViewInit() {
  this.ps.update();
}
```

Is that correct way of doing things?

**Comment by sconix** [comment]
I think this is some sort of perfect-scrollbar bug, but I have "fixed" it in the component just forcing it to stay right with setting css style with important flag. Would be nice to get fixed in perfect-scrollbar, but since I don't have time to try reproduce it without Angular I did the quick fix.

**Comment by hir06** [comment]
Hi, I am still facing this issue anyone found the solution? moreover @moniuch can you share the import you used for PerfectScrollbarDirective?

**Comment by sconix** [comment]
You can just have a look of the component style file in this library. There are those couple styles with !important that force the rail to stay its correct position.

**Comment by hir06** [comment]
will it help when container size has been modified? I have a dynamic height container which doesn't show scroll-bar initially whereas after updating or performing any action it brings it up

**Comment by sconix** [comment]
Styles only help to the PS bug that on some cases it miss places the scrollbars to the wrong side. If your issue is that the scrollbars wont update after container size is changes for that you need to use the update function call. So update call might be needed after the container size has changed. Although I do not know why since I have not seen this happening and this library should have resize observer that calls the update always when parent container size changes.

**Comment by hir06** [comment]
yup it has resize observer but when I compute the initial height of container via typescript it doesn't bring scroll-bar

**Comment by moniuch** [comment]
@hir06 Unfortunately I don't have this code anymore as I moved to another project where I am not using PS (yet?). I am thinking - would wrapping the resize invocation inside a `setTimeout` help?

**Comment by hir06** [comment]
Thanks @moniuch  will give it a try.
