### ISSUE TITLE
PerfectScrollbarComponent.html:6 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: 'true'. 

### ISSUE THREAD

**Issue by sidsamant** [zefoy/ngx-perfect-scrollbar#74]
https://plnkr.co/edit/hGxesG1ghKRrkVIaBsvv?p=preview

The error shows up on Chrome Debugger console.

A similar error has been marked as closed:
https://github.com/zefoy/ngx-perfect-scrollbar/issues/63

Not sure where I am wrong.

**Comment by sconix** [comment]
It looks like you have found an another change detection bug. I will release a new version later today which should fix the problem.

**Comment by sidsamant** [comment]
Sounds good. Thanks for looking at it.

**Comment by sconix** [comment]
This should be fixed in the 4.5.6.

**Comment by sidsamant** [comment]
That fixed it. Thanks again.

https://plnkr.co/edit/z0yGGNbteM2HacX2WM75?p=preview

**Comment by untitledlt** [comment]
I'm still getting this error on 4.8.4 but only if i specify `[scrollIndicators]="true"` or `[autoPropagation]="true"` attributes.

**Comment by hudzenko** [comment]
I'm still getting this error on 4.8.4 but only if i specify [scrollIndicators]="true" or [autoPropagation]="true" attributes too!!

**Comment by sconix** [comment]
Hmm those are on in the example and there is no error, but I will check the code maybe there is still one detectChanges missing.
